name: hello-cloud   # The name of the package
version: '0.1'
summary: hello cloud cli app  # Short one line summary
description: |  # A more detailed description of the app and it's functionality
  this is a test
confinement: devmode  # 'strict', 'classic' or 'devmode'. I've only tested devmode so far.
base: core20  # Snap core. 'core18' is equivalent to Ubuntu 18.04. Options: 'core', 'core18', 'core20'
grade: devel  # 'devel' or 'stable' based on app it's ready for release

parts:  # Where the app, files and dependencies are defined.
  hello:  # Pulled from setup.py
    plugin: python  # Defines the runtime plugin
    source: .   # Files are in the current directory. This can be almost anything. A .deb, a remote source, etc.

apps:   # Exposes the executable to the host system.
  hello:  # Same name as the 'part' defined above.
    command: hello.sh
    plugs:
      - network   # Allows the snap in interface with the network. Not needed in devmode but might be in strict.
